version: '3'

services:
  nginx:
    image: nginx
    container_name: server-nginx
    ports:
      - "8081:80"

  httpbin:
    image: kennethreitz/httpbin
    container_name: server-httpbin
    ports:
      - "8082:80"

  echo:
    image: ealen/echo-server
    container_name: server-echo
    ports:
      - "8083:80"

  python:
    image: python:3-alpine
    container_name: server-python
    command: python -m http.server 80
    ports:
      - "8084:80"

  envoy:
    image: envoyproxy/envoy:v1.29-latest
    container_name: envoy
    volumes:
      - ./envoy_routing_config.yml:/etc/envoy/envoy.yaml
    ports:
      - "10000:10000"
      - "9901:9901"
    depends_on:
      - nginx
      - httpbin
      - echo
      - python